### ISSUE TITLE
Feature Request: Additional layer to separate aggressive and neutral/friendly mobs.

### ISSUE THREAD

**Issue by BeekeeperAlex** [webbukkit/dynmap-mobs#6]
I like to show every mob available in the config (aside from the mobs that don't actually exist without extra plugins such as dolphin, scorpion, etc.) but some people only want to see the hostile mobs without all the animals, or all the animals without the hostile mobs.

The minimum to satisfy this feature request would be to simply hard-code a third layer and make this layer include neutral NPCs. Then make the "mobs" layer only include hostile mobs.

The awesome way to implement this feature would be to allow the user to configure custom layers, specifying the mobs/NPCs/vehicles that should appear in that layer. A "layers" section where you could define an array of layers and their properties, including a new "entities" property specifying which mobs/NPCs/vehicles to show in that layer.

Here is an example default config.yml file:

```
#dynmap-mobs configuration
update:
    period: 5.0
    vehicleperiod: 10.0
    resolution: 1.0
    hideifshadow: 4
    hideifundercover: 15
layers:
    Vehicles:
        entities:
            - 'explosive-minecart'
            - 'hopper-minecart'
            - 'powered-minecart'
            - 'spawner-minecart'
            - 'storage-minecart'
            - 'minecart'
            - 'boat'
        hidebydefault: false
        layerprio: 10
        tinyicons: false
        nolabels: false
        minzoom: 0
        inc-coord: false
    Hostile Mobs:
        entities:
            - 'creeper'
            - 'skeleton'
            - 'zombie'
            - 'blaze'
            - 'ghast'
            - 'silverfish'
            - 'slime'
            - 'spider'
            - 'zombiepigman'
            - 'enderdragon'
            - 'cavespider'
            - 'spiderjockey'
            - 'enderman'
            - 'witherskeleton'
            - 'wither'
            - 'zombievillager'
            #- 'fireogre'
            #- 'caveogre'
            #- 'ogre'
            #- 'flamewraith'
            #- 'wraith'
            #- 'werewolf'
            #- 'shark'
        hidebydefault: false
        layerprio: 10
        tinyicons: false
        nolabels: false
        minzoom: 0
        inc-coord: false
    NPCs:
        entities:
            - 'wolf'
            - 'snowgolem'
            - 'cow'
            - 'pig'
            - 'chicken'
            - 'squid'
            - 'sheep'
            - 'villager'
            - 'mooshroom'
            - 'tamedwolf'
            - 'ocelot'
            - 'cat'
            - 'golem'
            - 'witch'
            - 'bat'
            - 'vanillahorse'
            - 'horse'
            #- 'boar'
            #- 'polarbear'
            #- 'bear'
            #- 'duck'
            #- 'bigcat'
            #- 'deer'
            #- 'wildwolf'
            #- 'bunny'
            #- 'bird'
            #- 'fox'
            #- 'dolphin'
            #- 'fishy'
            #- 'kitty'
            #- 'hellrat'
            #- 'rat'
            #- 'mouse'
            #- 'scorpion'
            #- 'turtle'
            #- 'crocodile'
            #- 'ray'
            #- 'jellyfish'
            #- 'goat'
            #- 'snake'
            #- 'ostrich'
        hidebydefault: false
        layerprio: 10
        tinyicons: false
        nolabels: false
        minzoom: 0
        inc-coord: false
```

With this configuration you can remove the current "mobs" node entirely. If a mob/NPC/vehicle is not included in a specified layer then it is assumed to be disabled. In my example default config all mobs would be included in the three default layers, with the mobs from mo' creatures mod commented out by default.

It also eliminates the "name" property for the layers because each node under "layers" is the name of a layer. It would be great to be able to create as many layers as I want and have each of those layers show only the entities I'm interested in. Sometimes I may want to hunt a particular mob or group of mobs. In this way I could set up a layer that showed only the mobs I was interested in.
